name: elmix_sqlite
description: SQLite storage adapter for Elmix.
version: 0.1.0-dev
publish_to: none
resolution: workspace

environment:
  sdk: ^3.11.0

dependencies:
  elmix_engine: 0.1.0-dev
  sqlite3: ^3.3.1

dev_dependencies:
  test: ^1.31.1
