name: elmix
publish_to: none
description: Self-contained backend framework with dynamic schemas, SQLite persistence, APIs, auth, and client.
environment:
  sdk: ^3.11.0

workspace:
  - packages/elmix_engine
  - packages/elmix_sqlite
  - packages/elmix_server
  - packages/elmix_admin
  - packages/elmix_client
  - packages/elmix_cli

dev_dependencies:
  very_good_analysis: ^10.2.0
