import 'dart:convert';
import 'dart:io';

const _releaseFiles = <String, String>{
  'index.html': 'text/html',
  'main.client.dart.js': 'application/javascript',
};

Future<void> main() async {
  final build = await Process.run(
    Platform.resolvedExecutable,
    const <String>['run', 'jaspr_cli:jaspr', 'build'],
  );
  stdout.write(build.stdout);
  stderr.write(build.stderr);
  if (build.exitCode != 0) {
    exitCode = build.exitCode;
    return;
  }

  final assets = <String, String>{};
  for (final entry in _releaseFiles.entries) {
    final file = File('build/jaspr/${entry.key}');
    if (!file.existsSync()) {
      stderr.writeln('Expected generated asset is missing: ${file.path}');
      exitCode = 1;
      return;
    }
    assets[entry.key] = base64Encode(await file.readAsBytes());
  }

  final output = File('lib/src/generated/admin_assets.g.dart');
  await output.parent.create(recursive: true);
  await output.writeAsString(_renderAssetBundle(assets));
  stdout.writeln('Generated ${output.path}.');
}

String _renderAssetBundle(Map<String, String> assets) {
  final buffer = StringBuffer('''
// GENERATED CODE - DO NOT MODIFY BY HAND.
// Generated by tool/build_admin.dart from the Jaspr client build.
// ignore_for_file: lines_longer_than_80_chars, public_member_api_docs

const adminControlPlaneAssetContentTypes = <String, String>{
''');
  for (final entry in _releaseFiles.entries) {
    buffer.writeln("  '${entry.key}': '${entry.value}',");
  }
  buffer
    ..writeln('};')
    ..writeln()
    ..writeln('const adminControlPlaneEncodedAssets = <String, String>{');
  for (final entry in assets.entries) {
    buffer.writeln("  '${entry.key}': '${entry.value}',");
  }
  buffer.writeln('};');
  return buffer.toString();
}
